### ISSUE TITLE
No frontend include

### ISSUE THREAD

**Issue by gewaechshaus** [magepal/magento2-googletagmanager#11]
Hey there,

i just installed m2-gtm via composer as provided in the readme.
It's a Magento 2.1.2 system running on nginx/php7-fpm with varnish and haproxy in front.

However, I can't bring the code up on frontend. We're using a custom theme in this case. First thing I tried is to copy the layout xml in our default. xml <body> node

       <referenceContainer name="after.body.start">
            <block class="MagePal\GoogleTagManager\Block\Tm" name="magepal_gtm_datalayer" as="magepal_gtm_datalayer" template="data_layer.phtml" cacheable="false"/>
            <block class="MagePal\GoogleTagManager\Block\GtmCode" name="gtm_code" as="gtm_code" template="gtm_code.phtml" />
        </referenceContainer>

and put over the template files
https://goo.gl/XCrrY6

Any ideas?

Best
Jan

**Comment by srenon** [comment]
They should not be a need to copy the template files. Is the config showing up in admin?

**Comment by gewaechshaus** [comment]
@srenon 

> They should not be a need to copy the template files. 
Ok, I removed all related folders...

> Is the config showing up in admin?
For sure... I already added my ID etc.
https://goo.gl/mpfBvs

**Comment by srenon** [comment]
Flush all your caches.. Also take a look at $this->_cookieHelper->isUserNotAllowSaveCookie() in https://github.com/magepal/magento2-googletagmanager/blob/master/Block/GtmCode.php#L64 and see if that setting is causing your issue

**Comment by gewaechshaus** [comment]
@srenon - many thanks... As you can imagine, I did flush them and clean them manualy with rm -rf command that shouldn't be the issue.

But I remember that 

       if (!$this->helper('Magento\Cookie\Helper\Cookie')->isUserNotAllowSaveCookie())

did bug in the native analytics template, so this might be the point.
We'll know in a few minutes...

**Comment by gewaechshaus** [comment]
@srenon - Bingo... Does work:

     if (!$this->_gtmHelper->isEnabled()) {

**Comment by srenon** [comment]
If you want you can create a PR and I removed it since it seem to do more bad than good

**Comment by gewaechshaus** [comment]
Ok

**Comment by srenon** [comment]
@gewaechshaus ... thanks
