### ISSUE TITLE
The module does not working with FPC

### ISSUE THREAD

**Issue by maximehuran** [magepal/magento2-googletagmanager#16]
I have some problems with the DataLayer when Full Page Cache is enabled.
I tried to make the block non cacheable but nothing changes.

Why can I resolve the problem ?

Thank you :)

**Comment by srenon** [comment]
@maximehuran ... this should have been fixed in https://github.com/magepal/magento2-gmailsmtpapp/issues/30#issuecomment-269693863 

What version and edition (ee/ce) of magento?

**Comment by maximehuran** [comment]
I think it's a problem on my override. Without it, it seems work perfectly. 
But I have a question. How Magento 2 knows this block doesn't have to be cached ? I didn't find some code which tell it to Magento.

Thank you

**Comment by srenon** [comment]
see https://github.com/magepal/magento2-googletagmanager/blob/master/Block/Tm.php#L75

**Comment by maximehuran** [comment]
Oh ! I didn't see it ^^ Thank you very much :)
