### ISSUE TITLE
Adding data in the product view Data Layer

### ISSUE THREAD

**Issue by tempo-ruud** [magepal/magento2-googletagmanager#19]
Hi Guys,

Thanks for sharing this amazing module. Our marketing manager asked us for additional data, which he would like to see on the product view datalayer.

Can you please add price to the product view datalayer.

Thanks.

**Comment by srenon** [comment]
@tempo-ruud ... I'll review this shortly... but if I remember correctly getting the price for bundle and configurable product was an issue.

**Comment by grantkemp** [comment]
@tempo-ruud  its pretty easy to get this in tag manager - just make sure you add a div id to the price and it takes  a few seconds

**Comment by srenon** [comment]
@tempo-ruud ... should be fixed, let me know if you have any more issue after updating to the current version
