### ISSUE TITLE
Events configurations

### ISSUE THREAD

**Issue by gotogg** [magepal/magento2-googletagmanager#2]
Hi, first of all thanks for the code you developed, is the only free one i could find. 

The instalation works perfectly and analytics reads the common navigation data, but i have doubts when i try to configure specific events. 
I don't know how to make Google Tag Manager read the specific data layer attributes. 

For example for customer.isLoggedIn i do this:

> Tag configuration:
> Product: Analytics
> Tag type: Universal analytics
> ID: myanalyticsid
> Type: Event

> Tag configuration:
> Product: Analytics
> Tag type: Universal analytics
> ID: myanalyticsid
> Type: Event
> Category: {{Event}}
> Action: customer.isLoggedIn
> Label: (in blank)
> Value: (in blank)
> 
> Fire on/Trigger: 
> Event: Personalized Event
> Fire On: customer.isLoggedIn

I sure that my configuration is wrong. ¿Can you help me? I think that with one example i wouldn't have problems with the others data layers.

Thanks for the code again!

**Comment by srenon** [comment]
I was thinking about create a javascript layer, would this be more helpful?

Try creating a data layer variable 

![image](https://cloud.githubusercontent.com/assets/1415141/14301155/6dff1b4a-fb63-11e5-81d0-8bbcdd2b38c2.png)

Then

![image](https://cloud.githubusercontent.com/assets/1415141/14301378/4d416456-fb65-11e5-90f8-4ddf0c702a37.png)

**Comment by Serge-Wiki** [comment]
Hi guys, maybe you could help. I’m new to GTM integration and would like to create Event for E-commerce tracking, but cant find the event name which I could use to create a custom trigger.
Is my module working correct, or do I do something wrong?

Thanks a lot
![gtm](https://user-images.githubusercontent.com/31511015/29925810-32b6cf88-8e6a-11e7-84f3-2fb18e386717.png)

**Comment by srenon** [comment]
@Serge-Wiki ... can you create a new issue and I'll take a look.

Thanks

**Comment by Serge-Wiki** [comment]
Hey, srenon
I've created a new issue:
https://github.com/magepal/magento2-googletagmanager/issues/25
