### ISSUE TITLE
“already exists in context object” Errors

### ISSUE THREAD

**Issue by serafinbartosz** [magepal/magento2-googletagmanager#20]
The setup:di:command fail, and complain.
solution:
http://magento-quickies.alanstorm.com/post/138686669515/quick-note-on-already-exists-in-context-object

**Comment by MindConflicts** [comment]
Confirmed:

`MagePal\GoogleTagManager\Block\Data\Product
		Incorrect dependency in class MagePal\GoogleTagManager\Block\Data\Product in /var/www/magento-2/vendor/magepal/magento2-googletagmanager/Block/Data/Product.php
\Magento\Catalog\Helper\Data already exists in context object
Total Errors Count: 1
Errors during compilation:
	MagePal\GoogleTagManager\Block\Data\Product
		Incorrect dependency in class MagePal\GoogleTagManager\Block\Data\Product in /var/www/magento-2/vendor/magepal/magento2-googletagmanager/Block/Data/Product.php
\Magento\Catalog\Helper\Data already exists in context object
Total Errors Count: 1
Errors during compilation:
	MagePal\GoogleTagManager\Block\Data\Product
		Incorrect dependency in class MagePal\GoogleTagManager\Block\Data\Product in /var/www/magento-2/vendor/magepal/magento2-googletagmanager/Block/Data/Product.php
\Magento\Catalog\Helper\Data already exists in context object
Total Errors Count: 1`

**Comment by srenon** [comment]
@serafinbartosz @MindConflicts .... Thanks

Please try the latest version
