### ISSUE TITLE
Auto redirect 400 when checkout.

### ISSUE THREAD

**Issue by duynguyentien** [magepal/magento2-googletagmanager#21]
I have problem when using magento2-googletagmanager on magento 2.0.7.

When i checkout, link checkout auto add the token (ex:#PmwUKSLfOxMA4WKY.97) then it auto redirect to page 404.

Please help me.

Thank you so much.

**Comment by srenon** [comment]
@duynguyentien ... does this error go away if you disable the module?

**Comment by duynguyentien** [comment]
Hi @srenon ,

Yea, If i disable the module, The checkout works fine and link checkout does not contain token.

Thank you !

**Comment by srenon** [comment]
Are you using a custom/customize checkout?

There is no feature/code in the module that should cause it to add a token to the URL.

The quickest way to debug is to:
1. Open up code Chrome  Developer Tools
2. Go to Network tab
3. Go to XHR  (filter)
4. enable "Preserve log" 
5. reload page
6. review all the request to see which is returning an error
