### ISSUE TITLE
Order Data Layer attributes not loading on checkout_cart_index

### ISSUE THREAD

**Issue by willfrombrazil** [magepal/magento2-googletagmanager#23]
Magento CE v2.1.7
magepal/magento2-googletagmanager v2.0.2

On /checkout/onepage/success/ the only data layer attributes I'm receiving are:

`<script type="text/javascript">
--
  | window.dataLayer = window.dataLayer || [];
  | dataLayer.push({"ecommerce":{"currencyCode":"BRL"},"pageType":"checkout_cart_index","list":"cart","customer":{"isLoggedIn":false},"cart":{"hasItems":false}});
  | </script>`

Shouldn't this page list the following data layer attributes as well?

Order

transactionId
transactionAffiliation
transactionTotal
transactionShipping
transactionTax
transactionCouponCode
transactionDiscount
transactionSubTotal
transactionProducts[].sku
transactionProducts[].name
transactionProducts[].price
transactionProducts[].quantity

**Comment by srenon** [comment]
Take a look at https://github.com/magepal/magento2-googletagmanager/issues/15 

You are viewing the cart page and not the order success page

**Comment by lennartbee** [comment]
In our case an array in an array was made in MagePal\GoogleTagManager\Model\Order, I changed $result[] = $transaction; to $result = $transaction; which worked for us

**Comment by srenon** [comment]
$result[] = $transaction; should be correct ... for muliti-shipping orders

**Comment by willfrombrazil** [comment]
@srenon thanks for the info. I've confirmed I'm on pageType: checkout_onepage_success.

Do you know why the transaction data layer information shows up on Tag Assistant Plugin but not on the Google Tag Manager preview tab?

![download](https://user-images.githubusercontent.com/24959516/28190963-7d96d86a-6825-11e7-8487-d3c0e55fb76f.png)

What I'm trying to accomplish is to pass data layer information as User-Defined Variables on GTM, so I can add this info on CustomTags (eg: add transaction value and products to Facebook Conversion Pixels). But GTM isn't getting the transaction data variables:

![not working](https://user-images.githubusercontent.com/24959516/28190897-42c0207a-6825-11e7-9e40-8092da93e609.png)

Here's a video of the steps I'm taking: https://youtu.be/k9nRURoyqSo

**Comment by srenon** [comment]
@willfrombrazil ...

Please upgrade to 2.0.3 and let me know if you are still having issues.

Thanks for the detailed debugging information...

**Comment by willfrombrazil** [comment]
@srenon - thank you for this very helpful plugin!

I've tried to update via the component manager and got a error message. Will open another tread as it's a different issue.

**Comment by grantkemp** [comment]
@willfrombrazil  are you looking under the wrong event? Do you have a shared instance - then I can help you debug?

**Comment by srenon** [comment]
@willfrombrazil ... Are you still having issues?
