### ISSUE TITLE
Crashing Component Manager

### ISSUE THREAD

**Issue by willfrombrazil** [magepal/magento2-googletagmanager#24]
v2.0.3

--
MagePal GTM seems to be crashing the Component Manager, which stays with the message "please wait" infinitely: https://youtu.be/-vZIEGhN5N0

"Couldn't get available versions for package magepal/magento2-googletagmanager"
====
[dellarte@sipmia1-17 html]$ php bin/magento module:status|grep -i googletag
MagePal_GoogleTagManager
====

**Comment by srenon** [comment]
@willfrombrazil ... From all my research this is a core bug in Magento

see https://github.com/magepal/magento2-gmailsmtpapp/issues/70

Can you install from the command line?

```composer update magepal/magento2-googletagmanager:2.0.3```

**Comment by willfrombrazil** [comment]
OK, it seams this issue is related to this Magento 2 bug
https://github.com/magento/magento2/issues/6718

Thanks for the info.
