### ISSUE TITLE
Magento 2.0.6 doesn't load js and css after I enable the module

### ISSUE THREAD

**Issue by alexcrz** [magepal/magento2-googletagmanager#3]
Hi, I'm having an issue using this module. Basicly my installation works fine , but after I enable the module and insert my id , my website just stops loading the js and css , and I can't even login anymore into the admin panel , it just stops on the /admin123/admin page , press login and nothing happends. If I set the module off from mysql , deploy and clean , everything starts to work back.

**Comment by srenon** [comment]
Is it possible for you to disable the the current custom theme?

**Comment by srenon** [comment]
What version of php are you running?

**Comment by alexcrz** [comment]
yes I can do that , just a moment , and my php is PHP Version 5.6.21

**Comment by alexcrz** [comment]
If I change the theme to blank or luma , just by clearing the cache , I get Failed to load resource: the server responded with a status of 404 (Not Found) on css and js..

**Comment by srenon** [comment]
Does the page work fine, except for the static content (css/js)? Do you get the same issue on the front and backend?

**Comment by srenon** [comment]
Are you installing using composer or manually creating the folder structure?

**Comment by alexcrz** [comment]
yes , the page works fine except for the static content , and I'm installing it by just creating the folder structure , and after I enable it with php -f bin/magento module:enable MagePal_GoogleTagManager

**Comment by srenon** [comment]
Try

```bash
php -f bin/magento setup:upgrade
php -f bin/magento setup:static-content:deploy
```

**Comment by alexcrz** [comment]
I have already did those commands.. also clean , reindex ecc.. nothing works..

**Comment by srenon** [comment]
I just tested it on a fresh installed v2.0.7, before I install this module I was having similar css/js issues which the above command fixed.

I dont think it is a module issue but is instead cause after the module is install because the static content need to be refresh

What mode is magento running in http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html

Try different combination of and make sure you pub folder have the correct permission

http://magento.stackexchange.com/questions/64857/css-and-javascript-files-are-not-loading-after-magento-2-installation

**Comment by srenon** [comment]
Enable the module then go to the frontend and view page source, and search for "Google Tag Manager"

**Comment by alexcrz** [comment]
How do I check what mode is magento running ? and yes , the folders have the right permissions , I run chmod 777 pub -R and chmod 777 var -R before and after deploy..

**Comment by srenon** [comment]
```php bin/magento deploy:mode:show```

I (think) that information is pull from MAGE_MODE in  app/etc/env.php

**Comment by alexcrz** [comment]
It says Current application mode : default.

**Comment by srenon** [comment]
I going to close this issue, since you have not reply in a while
