### ISSUE TITLE
No output on frontend on magento 2.1

### ISSUE THREAD

**Issue by F-Gueguen** [magepal/magento2-googletagmanager#5]
Hello,

I installed this extension on a fresh magento 2.1 (sole new extension), on php 7.0.7, nginx, http2.
I needed to install it by copying the files because the dependencies are not up to date, and I can access / configure the extension in the admin. But on the frontend (with default template, no tweak but the logo) nothing appear. I flushed every cache, including my browser's, but nothing change.

I have no idea how to fix it myself since I'm only used to develop on magento 1, didn't touch the 2 yet.

Regards,

François

**Comment by F-Gueguen** [comment]
I also tried to change the template just in case, but nothing. On frontend, it's just as if I didn't install it.

**Comment by srenon** [comment]
@F-Gueguen ... I'm not able to reproduce  your issue on Magento 2.1 Php7.0.7 Apache. I updated composer to support M2.1.

Can you check your php/magento error logs? Do you have json_encode installed?

Please let me know if you still having issues.

**Comment by F-Gueguen** [comment]
@srenon, I found the bug. It's in the GtmCode block, "isUserNotAllowSaveCookie" returns 1 but I allowed the cookies (and magento does save cookies), so it's not from your module.
Maybe beause of european compliance?
Is it a problem if I remove this condition?

Thank you

François

**Comment by srenon** [comment]
@F-Gueguen ... Sure

**Comment by lucasalfaro** [comment]
@F-Gueguen  I am running the same problem with magento 2.1. Could you explain a bit more in details how you solved the problem?
 I can see the function is

` protected function _toHtml() {
        if ($this->_cookieHelper->isUserNotAllowSaveCookie() || !$this->_gtmHelper->isEnabled()) {
            return '';
        }
        return parent::_toHtml();
    }`

Did you just deleted the $this->_cookieHelper->isUserNotAllowSaveCookie()  part?

Regards
