### ISSUE TITLE
The module prevents cache from varnish

### ISSUE THREAD

**Issue by F-Gueguen** [magepal/magento2-googletagmanager#6]
Hello,

when I enable the output for this module, varnish doesn't cache my pages anymore (I have an "X-Cache: MISS" in the varnish log). I have "X-Cache: HIT" when I disable it.

Regards,

François

**Comment by srenon** [comment]
@F-Gueguen .... I currently dont have varnish installed on my dev machine... could you do a quick test for me. Leave the this module disabled and enable the default google Google Analytics.... then check varnish again, are you having HIT or MISS?

**Comment by F-Gueguen** [comment]
@srenon I have a MISS too, that's really crappy since it's supposed to be out of the box.

**Comment by srenon** [comment]
@F-Gueguen .... since this see to be a core issue, it make take a while to get a solution .... could you provide more info on how to replicate it?

**Comment by F-Gueguen** [comment]
I have no special tweak, my magento is behind a varnish and when I use your module or basic google analytics varnish stops to cache.
I have a nginx http2 -> varnish 4.1 -> nginx -> magento 2.1 architecture, but I don't think it's the problem, the cache works well with/out other modules (from mageworx).

**Comment by srenon** [comment]
Does any of those modules display information on the frontend/view source?

**Comment by F-Gueguen** [comment]
Yes they do (rich snippets, hreflang, etc).

2016-08-11 19:32 GMT+02:00 Renon Stewart <notifications@github.com>:

**Comment by srenon** [comment]
Can you provide me a list of those module so i can review something? Or can you check in Company/Module/view/frontend/layout/xyz.xml are there any ``cacheable="false"`` 

Could you also try remove the 'cacheable' attribute in view/frontend/layout/default.xml and see what happen (remember to regenerate/clear cache)

**Comment by Danielc3** [comment]
I am also having an issue with this module invalidating M2's build in full-page caching on every page. The following block is responsible:

`<block class="MagePal\GoogleTagManager\Block\Tm" name="magepal_gtm_datalayer" as="magepal_gtm_datalayer" template="data_layer.phtml" cacheable="false"/>
`

As this is specified as cacheable=false and this is in default.xml FPC does not work on any page. If we remove cacheable=false then this will get cached and output repeat data. I believe the only way around this is to fundamentally change how the module works and to pull in the content via AJAX. Do you have any thoughts on this?

**Comment by srenon** [comment]
@Danielc3 I dont think using ajax will work. How would it insert tags on a page if ajax is technically a separate request.

I think we should open an issue with magento for GA since it is a core module with the same issue

**Comment by karmalis** [comment]
There is an odd bug with Magento that we found where if you set a block to be non cacheable, the whole page isn't cached.
We've founda  work around which goes something like this:

magepal/magento2-googletagmanager/Block/Tm.php
in __construct
add: $this->_isScopePrivate = true; 
just before parent::__

magepal/magento2-googletagmanager/view/frontend/layout/default.xml
remove cacheable="false"

**Comment by srenon** [comment]
@karmalis ... can you create a PR (so i dont make any mistake)?

**Comment by karmalis** [comment]
Will do

**Comment by srenon** [comment]
Thanks

**Comment by tomdollarmpd** [comment]
Just been through this on a project, here's the fix;

in:
/vendor/magepal/magento2-googletagmanager/view/frontend/layout/default.xml

remove cacheable="false" on the block

in:
/vendor/magepal/magento2-googletagmanager/Block/Tm.php

find function: __construct

add: 
$this->_isScopePrivate = true; 
just before parent::__

**Comment by karmalis** [comment]
Yeah Tom, i've already added a pull request for that particular bit :)

**Comment by srenon** [comment]
@karmalis @tomdollarmpd ... Thanks...

**Comment by srenon** [comment]
@F-Gueguen @Danielc3 ... Please download the new version and let me know if you still having issues with varnish cache
