### ISSUE TITLE
Is it possible to track VAT/Tax ?

### ISSUE THREAD

**Issue by karmalis** [magepal/magento2-googletagmanager#7]
It seems that the tracking does not track VAT and/or Tax. Might we be doing something wrong?

**Comment by srenon** [comment]
@karmalis ... I will add it shortly

**Comment by karmalis** [comment]
Many thanks. Don't want to be annoying or anything, but any possible eta?

**Comment by srenon** [comment]
@karmalis ... what variable have VAT amount $order->getTaxAmount()?

**Comment by karmalis** [comment]
I believe so yes. However keep in mind that the "revenue" needs to be excluding tax.
One way or another, if something doesn't work correctly, I could always help adjust things with the extension.

**Comment by srenon** [comment]
I just push a new version, did you manually download or use composer to install?

**Comment by karmalis** [comment]
We use composer, however we can switch to a manual version if required.

**Comment by srenon** [comment]
Please test and let me know if there is any issue... (using composer)

**Comment by karmalis** [comment]
Will do. Many thanks for the superfast ninja response btw.

**Comment by karmalis** [comment]
We have tested and it works as thought of although we had to make amends for our client specifically to show revenue excluding tax. Nevertheless a job well done, many thanks!

**Comment by srenon** [comment]
@karmalis thanks for reporting the issue.
